### ISSUE TITLE
Input blinking on iOS

### ISSUE THREAD

**Issue by CHEWX** [lcdsantos/jQuery-Selectric#148] opened 2016-11-10 16:27 UTC
Hi,

What does `<input class="selectric-input" readonly="readonly" tabindex="0">` actually do ?

On iOS when you have the following options: `disableOnMobile: false` and `nativeOnMobile: false`, the input shows a blinking icon when you open the nav.

This can be fixed by `display: none`, on the element, but what does it actually do ?

Thanks,
Tom

**Comment by gearsdigital** [comment] 2016-11-16 12:38
AFAIK is the input mentioned used to enable the "word search" feature. Could you provide a fiddle which outlines your blinking icon?

**Comment by tj-shapeways** [comment] 2016-12-07 19:17
@CHEWX You should not use `display: none`. This has a negative impact on keyboard navigation since `display: none` means the `input` is ignored. Instead, I found this css that seems to work:

```.selectric-input {
  position: absolute !important;
  top: 0 !important;
  left: 0 !important;
  overflow: hidden !important;
  clip: rect(0, 0, 0, 0) !important;
  margin: 0 !important;
  padding: 0 !important;
  width: 1px !important;
  height: 1px !important;
  outline: none !important;
  border: none !important;
  *font: 0/0 a !important;
  background: none !important;
  /**
  * Selectric creates an empty input and focuses on it,
  * then removes it. This causes issues with iOS.
  * Make the text transparent so the blinking cursor
  * is transparent, and make the text at least
  * 16px to avoid auto-zoom.
  *
  **/
  color: transparent;
  font-size: 16px;
}

**Comment by CHEWX** [comment] 2016-12-07 19:37
@tj-shapeways I want the input to be ignore if @gearsdigital is correct. As I do not want the word search feature.

Seems a huge hack to do that when I do not actually want the input...

**Comment by tj-shapeways** [comment] 2016-12-07 20:05
Using `color: transparent` [is a trick for hiding the blinking cursor](http://stackoverflow.com/questions/9333044/how-to-hide-blinking-cursor-in-input-text).

I have confirmed that `display: none` on the input causes issues with keyboard navigation, as the up/down keys will make the page scroll instead of selecting the options in the dropdown. Check out the [fiddle](https://jsfiddle.net/422uchjk/).

**Comment by gearsdigital** [comment] 2017-05-10 21:17
I'll close this issue for now. Feel free to reopen if needed.

**Closed by gearsdigital** 2017-05-10 21:17 UTC
